### ISSUE TITLE
for the more security concerned users

### ISSUE THREAD

**Issue by jrsmile** [healzer/DiscordEarsBot#14]
Hi there,

would it be possible to include the VOSK-api and/or VOSK-Websocket (Server) STT backend for recognition as well?
the model can run directly in the bot instance or on a dedicated server and there is no limit to message length.
no need for 3rd party services.

Code Example: [here](https://github.com/alphacep/vosk-api/blob/master/nodejs/demo/test_simple_async.js)

**Comment by healzer** [comment]
Thanks :) I'll be looking into this!
