### ISSUE TITLE
Bot does not post the transcribed messages into a text channel

### ISSUE THREAD

**Issue by Schadenfreude320** [healzer/DiscordEarsBot#2]
Hey, we wanted to use your bot for a friend with a hearing condition. Unfortunately, we were not able to convince your bot to actually post the transcribed messages into a text chat.
It joined our server and we also posted the command in a text channel like you described in your tutorials.

Interestingly, the bot seems to be able to transcribe our messages since they are outputed into the command shell.

I'm not really deep into your code but: Could it be that something is off with the return value of the function, handling the api, and the return value is always null?

We encountered another issue: The bots randomly disconnects from our voice channel. This usually happens if we use another language that the bot does not understand.

**Comment by healzer** [comment]
Hey, that's odd.

Would it be possible to join our Discord server and provide some detailed logs, our community / myself can help you identify the issue.

Thanks :)
Ilya

**Comment by toxygen001** [comment]
Healzer,

We are attempting to set the bot up for one of our deaf members on our server and are running into this exact issue. We can see the speech to text output in the log, but the bot wont output in the channel. It does respond to voice commands for music however. Was a fix found for this issue?
