### ISSUE TITLE
Bot randomly shuts down

### ISSUE THREAD

**Issue by privateryann1** [healzer/DiscordEarsBot#3]
```events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open './temp/audio_696169824824328234_cole_1607053526333.raw.wav'
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:136:12
    at FSReqCallback.oncomplete (fs.js:156:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './temp/audio_696169824824328234_cole_1607053526333.raw.wav'
}
```

**Comment by healzer** [comment]
Hi,

Are you running the bot on linux, windows or through docker?

**Comment by privateryann1** [comment]
> 
> 
> Hi,
> 
> Are you running the bot on linux, windows or through docker?

Linux, CentOS 8 latest version

**Comment by healzer** [comment]
Are you running it as root? It seems it cannot read/write files, but not exactly sure with so little info.

**Comment by privateryann1** [comment]
Yes I am running as root

**Comment by healzer** [comment]
Please consult our readme and use "PM2" to run the bot, that should automatically re-start the bot in case there's an odd crash.
