### ISSUE TITLE
Bot doesn't listen to some people

### ISSUE THREAD

**Issue by privateryann1** [healzer/DiscordEarsBot#4]
Okay so for some reason, the bot just ignores two specific people in my discord server. It just doesn't register that they are talking for some reason. One of them uses a Blue Yeti Mic and the other has a Blue Snowball Mic so the quality is good. There's no errors attached either which is odd.

**Comment by healzer** [comment]
That's odd indeed.
Do you see any pattern between the random crashes in your previous post and these?

Also, are any of your users using Web Discord instead of the desktop version?

**Comment by privateryann1** [comment]
I didn't really notice anything tbh :/
All the users are using the discord desktop app

**Comment by healzer** [comment]
Please keep me updated on this issue, is it still happening?
Does your server have enough privileges and memory (hard drive and RAM)?
How many users are you serving?

**Comment by privateryann1** [comment]
Yeah it still happens. Server has 1GB of memory and 25GB of HDD. The bot is running on a fresh install of the latest version of CentOS 8.2

There's usually around 2-6 people in the channel with the bot. Regardless of how many people, it seems to not work on specific people when they use a specific mic. For instance, the people who cannot be heard on their PC are able to be heard just fine on their phones.

**Comment by healzer** [comment]
Thanks :)
These people that have problems on PC, are they  on Mac/Linux/Windows?
*Ilya Nevolin*
ilja.nevolin@gmail.com
+32 (0) 489 56 00 94

**Comment by privateryann1** [comment]
Windows

**Comment by healzer** [comment]
I have released new versions of our discord bots, with many improvements. I would encourage you to re-install everything according to the readme instructions. Let me know how it goes :)
